version: '3.8'

services:
  eureka-server:
    image: eureka-server
    build:
      context: services-eureka
      dockerfile: Dockerfile
    container_name: eureka-service
    ports:
      - "8761:8761"
    networks:
      - webnet

  pizza-order-service:
    build:
      context: pizza-order
      dockerfile: Dockerfile
    container_name: pizza-order-service
    ports:
      - "8080:8080"
    depends_on:
      - kafka
      - config-service
      - eureka-server
    environment:
      CONFIG_URI: http://config-service:8888
      EUREKA_URI: http://eureka-server:8761/eureka
      KAFKA_URI: kafka:29092

    networks:
      - webnet
  kitchen-service:
    build:
      context: kitchen
      dockerfile: Dockerfile
    container_name: kitchen-service
    ports:
      - "8081:8081"
    networks:
      - webnet
    depends_on:
      - kafka
      - config-service
      - eureka-server
    environment:
      CONFIG_URI: http://config-service:8888
      EUREKA_URI: http://eureka-server:8761/eureka


  config-service:
    build:
      context: config-service
      dockerfile: Dockerfile
    container_name: config-service
    ports:
      - "8888:8888"
    depends_on:
      - eureka-server
    environment:
      - "EUREKA_URI=http://eureka-server:8761/eureka"
    networks:
      - webnet

  zookeeper:
    image: confluentinc/cp-zookeeper:6.0.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - "ZOOKEEPER_CLIENT_PORT=2181"
      - "ZOOKEEPER_TICK_TIME=2000"

  kafka:
    image: confluentinc/cp-kafka:6.0.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      - "KAFKA_BROKER_ID=1"
      - "KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181"
      - "KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092"
      - "KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
      - "KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT"
      - "KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1"
    command: bash -c "cub kafka-ready -b kafka:29092 1 10 && /etc/confluent/docker/run"

networks:
  webnet: