server:
  port: 8081

spring:
  application:
    name: kitchen-service
  config:
    import: optional:configserver:http://localhost:8083/
eureka:
  client:
    service-url:
      defaultZone: ${EUREKASERVER_URI}
management:
  endpoints:
    web:
      exposure:
        include: refresh