server:
  port: 8081

spring:
  kafka:
    listener:
      type: batch
      ack-mode: manual_immediate
    bootstrap-servers: ${KAFKA_URI:localhost:9092}
  config:
    import: optional:configserver:http://localhost:8088/
  application:
    name: kitchen-service
eureka:
  client:
    service-url:
      defaultZone: ${EUREKASERVER_URI:http://localhost:8761/eureka/}
management:
  endpoints:
    web:
      exposure:
        include: refresh